using System.Text.RegularExpressions;

namespace LogicFit.Infrastructure.Services;

/// <summary>
/// Allows only private backup keys generated by the central backup service.
/// This policy accepts both the legacy timestamp key and the current artifact/manifest keys.
/// </summary>
internal static class BackupFileNamePolicy
{
    private static readonly Regex Pattern = new(
        "^(?:[A-Za-z0-9][A-Za-z0-9_-]{0,127}-(?:\\d{8}-\\d{6}(?:-[0-9a-fA-F]{32})?|[0-9a-fA-F]{8})|manifest-[0-9a-fA-F]{32})\\.(?:bacpac|json)$",
        RegexOptions.CultureInvariant | RegexOptions.IgnoreCase,
        TimeSpan.FromSeconds(1));

    internal static bool IsSafe(string fileName) =>
        !string.IsNullOrWhiteSpace(fileName) &&
        string.Equals(fileName, Path.GetFileName(fileName), StringComparison.Ordinal) &&
        Pattern.IsMatch(fileName);
}
