// <auto-generated />
#nullable disable

using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Migrations;
using LogicFit.Infrastructure.Persistence;

namespace LogicFit.Infrastructure.Persistence.Migrations;

[DbContext(typeof(ApplicationDbContext))]
[Migration("20260726150000_AddLocalizedPermissionsAndMemberCrud")]
public partial class AddLocalizedPermissionsAndMemberCrud
{
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
        // The model snapshot already contains the complete target model. The
        // migration operations are defined in the companion migration file;
        // this generated metadata makes EF discover and apply it.
    }
}
